QA Process - Documentation
humanmade/altis-documentation pull request #356
Opened 2022-03-09 07:17 UTC by robindevitt

This pr adds a Codeception test that checks the documentation renders correctly ( Acceptance Test ).

[Original Issue ](https://github.com/humanmade/product-dev/issues/837)

2022-03-09 12:22 UTC, robindevitt commented
Hey @shadyvb if you get a gap to review this PR for me that would be great 👍🏼 

HM Linter is failing due to a minified CSS file, nothing related to this issue.

2022-03-09 15:55 UTC, shadyvb requested changes
@robindevitt can we also make sure the menu exists and has items, and that the content is populated ? just in case the content rendering hits a bug or something.

2022-03-10 08:53 UTC, robindevitt commented
> @robindevitt can we also make sure the menu exists and has items, and that the content is populated ? just in case the content rendering hits a bug or something.

@shadyvb I have add a check that makes sure the documentation link is shown as well as a test that navigates to the CMS module and in the nav and then confirms the CMS H1 is seen.

This should cover all the bases?

2022-03-10 10:48 UTC, shadyvb requested changes
LGTM, just a small suggestion to improve the running time by removing 4 additional requests.

2022-03-10 10:48 UTC, shadyvb commented on tests/acceptance/DocumentationCest.php
> +	}
I don't think it is necessary to do three separate tests to check the same page, it adds 3 times the requests. One test should be fine. eg:
```suggestion
	/**
	 * Documantation link is shown, and page renders correctly.
	 *
	 * @param AcceptanceTester $I Tester
	 */
	public function testDocumentationLink( AcceptanceTester $I ) {
		$I->wantToTest( 'Documantation link is shown, and page renders correctly.' );
		$I->loginAsAdmin();
		$I->amOnAdminPage( '/' );

		// See the Documentation link in menu.
		$I->moveMouseOver( '.altis-logo-wrapper' );
		$I->seeLink( 'Documentation' );
		
		// Click the link to open the documentation.
		$I->click( 'Documentation' );
		
		// See the main title.
		$I->seeElement( '.altis-ui__doc-title' );
		
		// Click to go to CMS Module docs.
		$I->see( 'CMS', 'li' );
		$I->click( 'CMS' );

		// See the CMS H1 title.
		$I->see( 'CMS', 'h1' );
	}
}
```

2022-03-11 08:29 UTC, shadyvb approved these changes

2022-03-11 08:29 UTC, merged