Fix ElasticPress instructions for re-indexing
humanmade/altis-documentation pull request #576
Opened 2024-07-15 14:15 UTC by mikelittle

The sub-command for re-indexing is now `sync`.
`index` is deprecated and will be removed in a future release.

2024-08-07 19:44 UTC, ferschubert-hm approved these changes
LGTM

2024-08-12 11:08 UTC, kovshenin approved these changes

2024-08-12 11:09 UTC, kovshenin requested changes
These commands are exactly the same.

2024-08-13 10:54 UTC, mikelittle commented
Close this as no longer relevant.

2024-08-13 10:54 UTC, closed without merging